### ISSUE TITLE
Make text wrap around userpics

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/freefeed-lite#23]
Users are sad about wasted space in the userpic column and are asking for same kind of text wrapping as desktop version shows on smaller screen.

On lite:
![image](https://cloud.githubusercontent.com/assets/7983303/8120627/0729d2b0-10aa-11e5-9402-6c87f6f8c12b.png)

On desktop:
![image](https://cloud.githubusercontent.com/assets/7983303/8120633/12b95c04-10aa-11e5-86c8-27ac8e42a48a.png)

NOTE: on Frf in iPhone version userpics were very small, so userpic column was not perceived as wasted space:
![image](https://cloud.githubusercontent.com/assets/7983303/8120637/1be05ac6-10aa-11e5-8686-4268c8bca8e4.png)

**Comment by SiTLar** [comment]
now the text wraps on small screens
