### ISSUE TITLE
Fontsize on comments is too small

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/freefeed-lite#26]
Fontsize on comments is the same as on technical info (timestamp, links etc), and it's noticeably smaller than in posts. Considering that comments is possibly the primary content, they should be the same size as posts.

![image](https://cloud.githubusercontent.com/assets/7983303/8126828/9d3b67be-10fa-11e5-949a-378b147cba6c.png)

NOTE: in Frf for iPhone fontsize was actually uniform:
![image](https://cloud.githubusercontent.com/assets/7983303/8126840/c109cb04-10fa-11e5-8aea-e33f3a108768.png)

**Comment by SiTLar** [comment]
font sizes adjusted
