### ISSUE TITLE
Escape HTML codes on post and comment

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/freefeed-lite#31]
![image](https://cloud.githubusercontent.com/assets/7983303/8218500/ffe4a664-154b-11e5-804e-bb47cc4f19dc.png)

**Comment by berkus** [comment]
Is this screenshot from lite or desktop?

**Comment by smallq-git** [comment]
Screenshot is from desktop. Post was created on lite and symbols are displayed correctly there.

**Comment by SiTLar** [comment]
fixed, now all HTML is escaped
