### ISSUE TITLE
Implement picture collapsing

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/freefeed-lite#33]
Desktop version now collapses thumbnails if there are more than 3 pictures attached to the post (see https://github.com/pepyatka/pepyatka-html/issues/137):

_first 3 pictures had been shown, and when combined thumbnail width exceeded 450px (i.e. when there're wide (landscape/panorama) images) there would be less than three, to a minimum of 1, so that single line of pictures displayed by default would never wrap unless manually expanded._

Need to implement that on lite as well.

**Comment by clbn** [comment]
Clarification on the feature currently implemented in pepyatka/pepyatka-html#137

It hides images that are not on the first row. So the first row is shown only. It might be 10 images in there, if they narrow enough.

**Comment by SiTLar** [comment]
done
