### ISSUE TITLE
[Verified] html tag is rendered

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/freefeed-lite#6]
In FF:
![image](https://cloud.githubusercontent.com/assets/7983303/7995474/c51c43e8-0b1e-11e5-9c14-266d815b4eeb.png)

In Vanilla:
![image](https://cloud.githubusercontent.com/assets/7983303/7995477/ce2eda22-0b1e-11e5-913b-9608f4fdc60a.png)

**Comment by smallq-git** [comment]
Is this intentional?

**Comment by berkus** [comment]
Looks like a serious xss vulnerability :)

**Comment by berkus** [comment]
Fixed in [46ba45f5c1]

**Comment by smallq-git** [comment]
Fixed: 
![image](https://cloud.githubusercontent.com/assets/7983303/8149915/a0d91afc-12de-11e5-9ee4-a258d192a28c.png)
